In [4]:
pip install scikit-learn-extra

   ---------------------------------------- 0.0/340.5 kB ? eta -:--:--
   -------- ------------------------------- 71.7/340.5 kB 1.9 MB/s eta 0:00:01
   ---------------------------------------  337.9/340.5 kB 5.2 MB/s eta 0:00:01
   ---------------------------------------- 340.5/340.5 kB 3.5 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
from sklearn_extra.cluster import KMedoids
import numpy as np

In [11]:
x=np.asarray([[1,2],[1,4],[1,0],[4,2],[4,4],[4,0]])
kmediods =KMedoids(n_clusters=2,random_state=0).fit(x)

In [12]:
kmediods.labels_

array([0, 0, 0, 1, 1, 1], dtype=int64)

In [13]:
kmediods.predict([[0,0],[4,4]])

array([0, 1], dtype=int64)

In [14]:
kmediods.cluster_centers_

array([[1., 2.],
       [4., 2.]])

In [15]:
kmediods.inertia_

8.0